apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
        - name: simple-pod
          image: nginx
          port:
            - containerPort: 80
